# Practical 6: Vectors Part 2

In [1]:
import numpy as np

## Q1. Create a Python list representing vector v = [2,-1, 3] and multiply it by scalar 4.

1. Show the output.
2. Explain why the result is incorrect from a linear algebra perspective.
3. Convert the vector to a NumPy array and repeat the operation.

In [7]:
v1 = np.array([2,-1,3])
v2 = [2,-1,3]
print(v1*4, v2*4, sep='\n')

[ 8 -4 12]
[2, -1, 3, 2, -1, 3, 2, -1, 3, 2, -1, 3]


It is incorrect because in linear algebra scalar multiplies to every element but here in list it will just repeat the vector 4 times

## Q2. Given vector a = [5, -3] and scalar $\lambda$ =-2

1. Compute λa.
2. Compare their magnitudes
3. Explain the effect on magnitude and direction.
Hint: to write $\lambda$ in markdown syntax, do the following:
```$\lambda$```

In [37]:
a = np.array([5,-3])
l = -2
print(a, a*l, sep='\n')
m1 = np.linalg.norm(a)
m2 = np.linalg.norm(l*a)
print(m1,m2, sep='\n')
print(m2/m1)

[ 5 -3]
[-10   6]
5.830951894845301
11.661903789690601
2.0


Magnutide has increased by absolute of lambda which is 2

since the lambda is negative, direction is reversed. 

## Q3. Create:

- Column vector shape (3,1)
- Row vector shape (1,4)
- Print the shape of the results

Add them using Numpy Broadcasting

In [15]:
c = np.array([[1, 2, 3]]).T
r = np.array([[1, 2, 3, 4]])
print(c.shape, r.shape, sep='\n')
print(r+c)

(3, 1)
(1, 4)
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


## Q4 . Create vector v = [1,2,3,4] and add scalar 5

Explain why NumPy allows this.

In [19]:
v = np.array([1, 2, 3, 4])
print(v + 5)


[6 7 8 9]


By broadcasting scalar converts to a vector: [5, 5, 5, 5] so they can be added together

## Q5. Given vector a = [1,2,3,4,5,6], compute its Euclidean norm manually and using NumPy.

Hint: By "manually," I mean solving it step by step using only basic NumPy functions.

In [30]:
a = np.array([1, 2, 3, 4, 5, 6])

norm1 = np.sqrt(np.sum(a**2))
norm2 = np.linalg.norm(a)
print(norm1, norm2, sep='\n')

9.539392014169456
9.539392014169456


## Q6. Generate a random vector of length 10 and normalize it. Print the norm before and after normalization

In [47]:
v = np.random.rand(10)
v1 = np.linalg.norm(v)
v2 = np.linalg.norm(v/v1)
print(v)
print("Before\n", v1)
print("After\n", v2)

[0.06707555 0.36541957 0.45914706 0.89417372 0.27065898 0.85138598
 0.19653631 0.39574202 0.504661   0.14382577]
Before
 1.5547071966092876
After
 1.0


## Q7. Compute the dot product of vectors

a = [1,2,3,4,5,6] & b = [0,-4,3,-3,6,5]
using:
1. Manual loop
2. NumPy np.dot() 

In [20]:
a = np.array([1,2,3,4,5,6])
b = np.array([0,-4,3,-3,6,5])
d1 = 0
d2 = 0
for i in range(len(a)):
    d1 += a[i] * b[i]
d2 = np.dot(a, b)
print(d1, d2)


49 49


## Q8. Verify the distributive property:


```$$a · (b + c) = a · b + a · c$$```

Hint: Generate three random numbers


In [ ]:
a = np.random.rand(2)
b = np.random.rand(2)
c = np.random.rand(2)
print(a, b, c, sep='\n')
print(np.dot(a, (b+c)))
print(np.dot(a, b)+np.dot(a, c))

[0.47042547 0.65041958]
[0.12104979 0.74598122]
[0.75235783 0.65283999]
1.3206938877574095
1.3206938877574093


## Q9: Compute the Euclidean distance matrix between every point in group A and every point in group B.


In [49]:
A = np.array([
[ 2, 1],
[ 5, 4],
[ 1, 6],
[ 7, 2]
])
B = np.array([
[0, 0],
[6, 3],
[3, 5]
])
print(A.shape, B.shape, sep='\n')

A1 = A[:, np.newaxis, :]
B1 = B[np.newaxis,:, :]
dif = A1 - B1
print(dif)
print(A1.shape, B1.shape, dif.shape, sep='\n')

sum_sq = np.sum(dif**2, axis=2)
dist_matrix = np.sqrt(sum_sq)

print(dist_matrix.shape)
print(dist_matrix)

(4, 2)
(3, 2)
[[[ 2  1]
  [-4 -2]
  [-1 -4]]

 [[ 5  4]
  [-1  1]
  [ 2 -1]]

 [[ 1  6]
  [-5  3]
  [-2  1]]

 [[ 7  2]
  [ 1 -1]
  [ 4 -3]]]
(4, 1, 2)
(1, 3, 2)
(4, 3, 2)
(4, 3)
[[2.23606798 4.47213595 4.12310563]
 [6.40312424 1.41421356 2.23606798]
 [6.08276253 5.83095189 2.23606798]
 [7.28010989 1.41421356 5.        ]]
